### ISSUE TITLE
macOS 13 public beta 6 - installation issue

### ISSUE THREAD

**Issue by NZRichard** [Juan-VC/Hackintosh-ASUS-Z690-P-WIFI#1]
Installation of **macOS 12.6** and all OS functions including sleep/wake and audio are faultless using this OC EFI folder. 
for this system:

Prime Z690-P DDR5, No WiFi
i7 12700K
Crucial 2 X 16 GB 4800  
Sapphire RX580 8GB

Installation of **macOS 13 public beta 6** freezes at Progress Bar using EFI folder for "Hackintosh-ASUS-Z690-P-WIFI":

- the installation freezes due to a KP at the start of the progress bar - bar is empty
- noticed NVRAM and LoadEarly errors using ocvalidate (OCAT) for OC 0.8.3 to check the config.plist from EFI folder

Thank you for sharing!

**Comment by NZRichard** [comment]
Update to last comment on 25 Sept. 2022:

1. The freeze-empty progress bar KP may be fixed by updating Lilu.kext to v.1.6.2 

3. The NVRAM issue may be resolved by deleting the "LegacyEnable" key which is not required for OC 0.8.3

4. The LoadEarly issue may be resolved by adding a "LoadEarly" key set to False at the end of each driver in UEFI/Drivers 

Credit - UtterDisbelief @ TM on Aug 3, 2022

**Comment by Juan-VC-gh** [comment]
Oh yeah, I forgot when uploaded OpenCore to type the version the repo is using currently. 

> * noticed NVRAM and LoadEarly errors using ocvalidate (OCAT) for OC 0.8.3 to check the config.plist from EFI folder

This is interesting will look into it soon trying to prepare an updated OpenCore config for when Ventura comes. If you have modified your config.plist you could also make a pull request, that is always appreciated as I no longer spend that much time setting up hackintosh setups.

**Comment by NZRichard** [comment]
Well, ocvalidate seemed to recognize the config as OC 0.8.3 so, I am going with that. Also, OC 0.8.3 is good for Ventura beta -> v.6 with the Lilu kext v.1.6.2 update. Will know more when we get Ventura RC next month some time. Went to request a Pull Request, but the form didn't open - am I missing something?

**Comment by Juan-VC-gh** [comment]
Never got a pull request, otherwise it would show as open/closed. You need to fork my repo, make the changes suggested there then create the pull request.

**Comment by Juan-VC-gh** [comment]
Fixed in release [0.0.2](https://github.com/Juan-VC/Hackintosh-ASUS-Z690-P-WIFI/releases/tag/0.0.2) and tested Ventura support with the release candidate
