### ISSUE TITLE
Black screen when install monterey

### ISSUE THREAD

**Issue by dragongt501** [Juan-VC/Hackintosh-ASUS-Z690-P-WIFI#2]
Hi bro, thank for your project.
I use Asus z690-P-Wifi
I use CPU i9 12900k
GPU RX6800
I used your EFI and config BIOS like you. But, when i select install Monterey, i got black screen.
I try to add agdpmod=pikera, but i got 
![image](https://user-images.githubusercontent.com/61512241/198819883-871297aa-c557-491c-b24c-dcd5fab4e997.png)
like this.
Thank for your help!

**Comment by Juan-VC-gh** [comment]
A log file might be in the root of the USB, try to find that and attach it here. As text from the picture is barely readable

Also seems there is a problem with your Bluetooth, do you use the same motherboard, same Wifi/BT card? If the answer is no to any of the previous then I cannot help much and would just recommend to create the usb mapping for yourself

**Comment by Juan-VC-gh** [comment]
Also try to boot adding boot args -v -x

by the way is your hardware exactly as mine, nothing extra nor less? If anything changes that is likely the culprit as having say an amd + nvidia gpu could cause trouble and so

**Comment by ghsssss** [comment]
13600KF可以用吗

**Comment by dragongt501** [comment]
Thank bro, i try map usb on window and use it. After that problem was fix.

**Comment by Juan-VC-gh** [comment]
> Thank bro, i try map usb on window and use it. After that problem was fix.

That totally makes sense, different CPU would yield a different usb mapping!
Had not thought on that before, glad it works enjoy :)
