### ISSUE TITLE
Is it support GeForce GTX 1080Ti？

### ISSUE THREAD

**Issue by DreamyDelight** [Juan-VC/Hackintosh-ASUS-Z690-P-WIFI#4]
Hi，

My hardware configuration is very similar to yours

Motherboard: ASUS PRIME Z690-P
CPU:  Intel Core i9-12900K

But the GPU is NVIDIA GeForce GTX 1080Ti, Can I use your EFI in my case?

**Comment by Juan-VC** [comment]
There is no driver support for any Nvidia card on recent macOS versions so you are out of luck
